name: Awesome Bot
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Awesome Bot
      run: gem install awesome_bot
    - name: Run Awesome Bot
      run: awesome_bot README.md --white-list hosxp.net
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: ab-results
        path: ab-results-README.md-filtered.json
